import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../src/App.jsx';
import { GUEST_KEY } from '../src/lib/model.js';
import { OPTIONS_KEY } from '../src/lib/taxonomy.js';

vi.mock('../src/lib/firebase.js', () => ({ auth: null, db: null, firebaseConfigured: false, friendlyError: (error) => error.message }));
const readSaved = () => JSON.parse(localStorage.getItem(GUEST_KEY)).games;
beforeEach(() => { localStorage.clear(); localStorage.setItem(GUEST_KEY, JSON.stringify({ version: 1, games: [] })); });

describe('Biblioteca local', () => {
  it('adiciona um jogo do catálogo com nota 4,5, edita e restaura ao abrir novamente', async () => {
    const user = userEvent.setup();
    const page = render(<App />);
    await user.click(await screen.findByRole('button', { name: 'Adicionar jogo', exact: true }));
    await user.type(screen.getByLabelText('Nome do jogo'), 'Hades');
    await user.click(screen.getByRole('button', { name: 'Selecionar Hades', exact: true }));
    await user.selectOptions(screen.getByLabelText('Sua lista'), 'completed');
    await user.click(screen.getByRole('button', { name: 'Avaliar com 4,5 estrelas' }));
    await user.type(screen.getByLabelText(/Sua avaliação/), 'Combate muito bom.');
    await user.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Adicionar jogo', exact: true }));
    await screen.findByRole('button', { name: 'Editar Hades', exact: true });
    expect(readSaved()[0]).toMatchObject({ title: 'Hades', rating: 4.5, status: 'completed', genre: 'Roguelike', review: 'Combate muito bom.', coverUrl: '/covers/1145360.jpg' });
    await user.click(screen.getByRole('button', { name: 'Editar Hades', exact: true }));
    await user.selectOptions(screen.getByLabelText('Sua lista'), 'platinum');
    await user.click(screen.getByRole('button', { name: 'Salvar alterações' }));
    await waitFor(() => expect(readSaved()[0].status).toBe('platinum'));
    page.unmount(); render(<App />);
    await screen.findByRole('button', { name: 'Editar Hades', exact: true });
    expect(screen.getAllByText('Platinado').length).toBeGreaterThan(0);
  });
  it('salva a ordem, filtra por gênero e exclui após confirmação', async () => {
    const user = userEvent.setup();
    const now = Date.now();
    const initial = ['Alpha', 'Beta', 'Gamma'].map((title, index) => ({ id: title, title, genre: index === 1 ? 'RPG' : 'Aventura', status: 'planned', rating: 0, coverUrl: '', review: '', rank: (index + 1) * 1024, createdAt: now, updatedAt: now }));
    localStorage.setItem(GUEST_KEY, JSON.stringify({ version: 1, games: initial }));
    render(<App />);
    await user.click(await screen.findByRole('button', { name: 'Mover Gamma para antes' }));
    await waitFor(() => expect(readSaved().map((game) => game.title)).toEqual(['Alpha', 'Gamma', 'Beta']));
    await user.selectOptions(screen.getByLabelText('Filtrar por gênero'), 'RPG');
    expect(screen.queryByRole('button', { name: 'Editar Alpha', exact: true })).toBeNull();
    await user.click(screen.getByRole('button', { name: 'Editar Beta', exact: true }));
    await user.click(screen.getByRole('button', { name: 'Excluir', exact: true }));
    expect(readSaved()).toHaveLength(3);
    await user.click(screen.getByRole('button', { name: 'Excluir jogo', exact: true }));
    await waitFor(() => expect(readSaved()).toHaveLength(2));
    expect(screen.getByText('Nenhum jogo deste gênero por aqui.')).toBeTruthy();
  });
  it('alterna o tema e informa que as contas dependem de configurar o Firebase', async () => {
    const user = userEvent.setup(); render(<App />);
    await user.click(screen.getByRole('button', { name: 'Ativar tema claro' }));
    expect(document.documentElement.dataset.theme).toBe('light');
    expect(localStorage.getItem('checkpoint.theme')).toBe('light');
    await user.click(screen.getByRole('button', { name: 'Minha conta' }));
    expect(screen.getByText(/O Firebase ainda não foi configurado/)).toBeTruthy();
    expect(screen.getByRole('button', { name: 'Entrar na minha conta' }).disabled).toBe(true);
  });
  it('preserva o formulário quando a imagem tem um protocolo inválido', async () => {
    const user = userEvent.setup(); render(<App />);
    await user.click(await screen.findByRole('button', { name: 'Adicionar jogo', exact: true }));
    await user.type(screen.getByLabelText('Nome do jogo'), 'Meu jogo');
    await user.type(screen.getByLabelText(/URL da capa/), 'javascript:alert(1)');
    await user.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Adicionar jogo', exact: true }));
    await screen.findByRole('alert');
    expect(screen.getByLabelText('Nome do jogo').value).toBe('Meu jogo');
    expect(readSaved()).toHaveLength(0);
  });
  it('cria lista e gênero pessoais, usa no jogo e mantém referências ao renomear', async () => {
    const user = userEvent.setup(); render(<App />);
    await user.click(screen.getByRole('button', { name: 'Configurações', exact: true }));
    await user.click(screen.getByRole('button', { name: 'Nova lista' }));
    await user.type(screen.getByLabelText('Nome da lista'), 'Quero revisitar');
    await user.click(screen.getByRole('button', { name: 'Salvar para mim' }));
    await user.click(screen.getByRole('button', { name: 'Gêneros', exact: true }));
    await user.click(screen.getByRole('button', { name: 'Novo gênero' }));
    await user.type(screen.getByLabelText('Nome do gênero'), 'Soulslike');
    await user.click(screen.getByRole('button', { name: 'Salvar para mim' }));
    const saved = JSON.parse(localStorage.getItem(OPTIONS_KEY)).options;
    const listId = saved.find((option) => option.kind === 'list').id;
    const genreId = saved.find((option) => option.kind === 'genre').id;
    await user.click(screen.getByRole('button', { name: 'Fechar', exact: true }));
    await user.click(screen.getByRole('button', { name: 'Adicionar jogo', exact: true }));
    await user.type(screen.getByLabelText('Nome do jogo'), 'Meu RPG');
    await user.selectOptions(screen.getByLabelText('Sua lista'), listId);
    await user.selectOptions(screen.getByLabelText('Gênero', { exact: true }), genreId);
    await user.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Adicionar jogo', exact: true }));
    expect(readSaved()[0]).toMatchObject({ status: listId, genre: genreId });
    await user.click(screen.getByRole('button', { name: 'Configurações', exact: true }));
    await user.click(screen.getByRole('button', { name: 'Editar Quero revisitar', exact: true }));
    await user.clear(screen.getByLabelText('Nome da lista'));
    await user.type(screen.getByLabelText('Nome da lista'), 'Rejogar');
    await user.click(screen.getByRole('button', { name: 'Salvar para mim' }));
    await user.click(screen.getByRole('button', { name: 'Arquivar Rejogar', exact: true }));
    await user.click(screen.getByRole('button', { name: 'Confirmar arquivamento' }));
    await user.click(screen.getByRole('button', { name: 'Fechar', exact: true }));
    expect(readSaved()[0].status).toBe(listId);
    expect(screen.getAllByText('Rejogar').length).toBeGreaterThan(0);
    await user.click(screen.getByRole('button', { name: 'Editar Meu RPG', exact: true }));
    expect(screen.getByRole('option', { name: 'Rejogar (arquivada)' }).value).toBe(listId);
    await user.click(screen.getByRole('button', { name: 'Avaliar com 4,5 estrelas' }));
    await user.click(screen.getByRole('button', { name: 'Salvar alterações' }));
    expect(readSaved()[0]).toMatchObject({ status: listId, rating: 4.5 });
  });
  it('mostra opções globais para conta comum sem controles de administração', async () => {
    const user = userEvent.setup(); render(<App />);
    await user.click(screen.getByRole('button', { name: 'Configurações', exact: true }));
    await user.click(screen.getByRole('button', { name: 'Opções globais', exact: true }));
    expect(within(screen.getByRole('dialog')).getByText('Jogando', { exact: true })).toBeTruthy();
    expect(screen.queryByRole('button', { name: 'Nova lista' })).toBeNull();
    expect(screen.queryByRole('button', { name: 'Editar Jogando' })).toBeNull();
    expect(screen.getByText(/Apenas o administrador pode alterá-las/)).toBeTruthy();
  });
});
