import { useEffect, useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { Users, UserPlus, Copy, Check, LoaderCircle, ArrowLeft } from 'lucide-react';
import Avatar from '../components/Avatar.jsx';
import Cover from '../components/Cover.jsx';
import Modal from '../components/Modal.jsx';
import { Stars } from '../components/Rating.jsx';
import useFriendLibrary from '../hooks/useFriendLibrary.js';
import { formatHours } from '../lib/model.js';
import { otherName, otherUid } from '../lib/friends.js';

export default function FriendsPage() {
  const { library, friends, notify } = useOutletContext();
  const [code, setCode] = useState('');
  const [selected, setSelected] = useState(null);
  const [removing, setRemoving] = useState(null);
  const [copied, setCopied] = useState(false);
  const uid = library.user?.uid;
  useEffect(() => { setCode(''); setSelected(null); setRemoving(null); setCopied(false); }, [uid]);
  const chosen = friends.accepted.find(entry => otherUid(entry, uid) === selected);
  const shared = useFriendLibrary(uid, chosen ? selected : null, library.taxonomy.options);
  const act = async (operation, message) => { try { await operation(); notify(message); } catch (failure) { notify(failure.message, true); } };
  const disabled = !friends.ready || friends.busy;
  if (!library.user) return <main className="workspace"><div className="page-heading"><div><div className="eyebrow">JOGAR É MELHOR COM COMPANHIA</div><h1>Amigos<span className="heading-period">.</span></h1></div></div><div className="empty-state"><div className="empty-icon"><Users size={32} /></div><h2>Entre na conta para adicionar amigos.</h2><p>Use Minha conta no cabeçalho. Seus amigos só veem a coleção depois de você aceitar o pedido.</p></div></main>;
  if (chosen) return <main className="workspace friend-library"><button className="text-button back-link" onClick={() => setSelected(null)}><ArrowLeft size={17} />Voltar aos amigos</button><div className="page-heading"><div><div className="eyebrow">COLEÇÃO COMPARTILHADA</div><h1>Biblioteca de {shared.profile?.displayName || otherName(chosen, uid)}<span className="heading-period">.</span></h1><p>Veja os jogos e avaliações do seu amigo.</p></div><Avatar src={shared.profile?.photoData} name={shared.profile?.displayName || otherName(chosen, uid)} className="friend-profile-avatar" /></div>
    {shared.error ? <div className="social-error" role="alert"><p>{shared.error}</p><button className="button secondary" onClick={shared.retry}>Tentar novamente</button></div> : !shared.ready ? <div className="loading-state" role="status"><LoaderCircle className="spin" /><p>Carregando a coleção...</p></div> : shared.games.length ? <div className="game-grid">{shared.games.map(game => <article className="friend-game-card" key={game.id}><div className="cover-wrap"><Cover src={game.coverUrl} title={game.title} /></div><h2>{game.title}</h2><div className="game-meta"><span>{shared.options.find(option => option.id === game.genre)?.label || game.genre}</span><span>{shared.options.find(option => option.id === game.status)?.label || game.status}</span></div><Stars value={game.rating} />{game.hoursPlayed > 0 && <p className="game-hours">{formatHours(game.hoursPlayed)} de jogo</p>}{game.review && <p className="friend-review">{game.review}</p>}<Link className="button secondary friend-review-button" to={`/reviews/${selected}/${game.id}`}>Ver avaliação de {game.title}</Link></article>)}</div> : <div className="empty-state"><h2>Esta coleção ainda está vazia.</h2></div>}
  </main>;
  return <main className="workspace friends-page">
    <div className="page-heading"><div><div className="eyebrow">JOGAR É MELHOR COM COMPANHIA</div><h1>Amigos<span className="heading-period">.</span></h1><p>Compartilhe sua coleção com quem também ama jogar.</p></div></div>
    <div className="friend-setup-grid"><section className="social-panel"><h2>Seu código de amigo</h2><p>Envie este código para a pessoa que você quer adicionar.</p><div className="copy-code"><input aria-label="Seu código de amigo" value={uid} readOnly onFocus={event => event.target.select()} /><button className="icon-button" aria-label="Copiar código de amigo" onClick={async () => { try { await navigator.clipboard.writeText(uid); setCopied(true); notify('Código copiado.'); } catch { notify('Selecione o código e copie com Ctrl + C.'); } }}>{copied ? <Check size={18} /> : <Copy size={18} />}</button></div></section>
      <section className="social-panel"><h2>Adicionar amigo</h2><form onSubmit={async event => { event.preventDefault(); await act(async () => { await friends.sendRequest(code); setCode(''); }, 'Pedido enviado. Aguarde a pessoa aceitar.'); }}><label htmlFor="friend-code">Código do seu amigo</label><div className="friend-add-row"><input id="friend-code" value={code} maxLength={140} onChange={event => setCode(event.target.value)} placeholder="Cole o código aqui" required /><button className="button primary" type="submit" disabled={disabled || !code.trim()}><UserPlus size={17} />Enviar pedido</button></div></form></section></div>
    <p className="sharing-note">Ao aceitar, vocês compartilham nome, foto, jogos, notas, avaliações marcadas como Amigos, listas, gêneros e atividades. Somente o dono pode editar a coleção. Remover a amizade encerra o acesso pelo site; informações já vistas ou copiadas não podem ser recolhidas.</p>
    {friends.error && <div className="social-error" role="alert"><p>{friends.error}</p><button className="button secondary" onClick={friends.retry}>Tentar novamente</button></div>}
    {!friends.ready && !friends.error && <div className="loading-state" role="status"><LoaderCircle className="spin" /><p>Carregando amigos...</p></div>}
    {friends.incoming.length > 0 && <section className="friend-section"><h2>Pedidos recebidos <span>{friends.incoming.length}</span></h2><div className="friend-list">{friends.incoming.map(entry => <article className="friend-row" key={entry.id}><Avatar name={entry.fromName} /><div><Link to={`/perfil/${entry.fromId}`}><strong>{entry.fromName}</strong></Link><span>Quer compartilhar a coleção com você.</span></div><div className="friend-actions"><button className="button primary" disabled={disabled} onClick={() => act(() => friends.accept(entry.id), 'Amizade aceita. Vocês já podem ver as coleções.')}>Aceitar</button><button className="button secondary" disabled={disabled} onClick={() => act(() => friends.remove(entry.id), 'Pedido recusado.')}>Recusar</button></div></article>)}</div></section>}
    {friends.outgoing.length > 0 && <section className="friend-section"><h2>Pedidos enviados</h2><div className="friend-list">{friends.outgoing.map(entry => <article className="friend-row" key={entry.id}><Avatar name="Jogador" /><div><strong>Aguardando aceitação</strong><span className="friend-uid">Código: {entry.toId}</span></div><button className="button secondary" disabled={disabled} onClick={() => act(() => friends.remove(entry.id), 'Pedido cancelado.')}>Cancelar pedido</button></article>)}</div></section>}
    <section className="friend-section"><h2>Seus amigos <span>{friends.accepted.length}</span></h2>{friends.accepted.length ? <div className="friend-list">{friends.accepted.map(entry => <article className="friend-row" key={entry.id}><Avatar name={otherName(entry, uid)} /><div><Link to={`/perfil/${otherUid(entry, uid)}`}><strong>{otherName(entry, uid)}</strong></Link><span>Coleção e atividades compartilhadas.</span></div><div className="friend-actions"><button className="button secondary" onClick={() => setSelected(otherUid(entry, uid))}>Ver biblioteca</button><Link className="button secondary" to={`/conversas?com=${otherUid(entry, uid)}`}>Conversar</Link><button className="text-button" disabled={disabled} onClick={() => setRemoving(entry)}>Remover amigo</button></div></article>)}</div> : friends.ready && <div className="friend-empty"><Users size={24} /><p>Seu próximo parceiro de jogo pode estar a um código de distância.</p></div>}</section>
    <Modal open={Boolean(removing)} onOpenChange={open => { if (!open) setRemoving(null); }} title="Remover amizade?" description="Vocês deixarão de acessar as coleções e atividades um do outro pelo site." busy={friends.busy} className="confirm-modal"><div className="modal-footer"><span /><div><button className="button secondary" disabled={friends.busy} onClick={() => setRemoving(null)}>Cancelar</button><button className="button primary" disabled={friends.busy} onClick={() => act(async () => { await friends.remove(removing.id); setRemoving(null); }, 'Amizade removida.')}>Confirmar remoção</button></div></div></Modal>
  </main>;
}
